services:
  stats-server:
    build: ewm-stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - EWM_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
    restart: on-failure

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    restart: on-failure

  ewm-service:
    build: ewm-service
    container_name: main-server
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - EWM_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
    restart: on-failure

  ewm-db:
     image: postgres:14-alpine
     volumes:
      - /var/lib/postgresql/data
     ports:
      - "6543:5432"
     environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=host
      - POSTGRES_PASSWORD=host
     restart: on-failure