DROP TABLE IF EXISTS hits CASCADE;
CREATE TABLE IF NOT EXISTS hits
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    app        VARCHAR(255),
    uri        VARCHAR(555),
    ip         VARCHAR(255),
    timestamp TIMESTAMP WITH TIME ZONE
                             );